config/routes.rb
Friends::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root :controller => "flight_searches", :action => 'index'

  resources :flight_searches
  resources :flights 
  resources :hotels
  resources :faq, only: :index
  match "flight-deals", :to => "flight_deals#index", :via => [ :get ]
  match "how-it-works", :to => "how_it_works#index", :via => [ :get ]


end

app/models/flight.rb
class Flight < ActiveRecord::Base
	attr_accessible :departure, :arrival, :price, :airline_id, :duration

	belongs_to :airline
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	def index
		@flights = Flight.where(:id => 1)
		respond_to do |format|
	      format.html
	      format.json do
	        if params[:datatable]
	          render(
	            :json => RemoteDatatable.new(
	              view_context, @flights, 
	              :flight_row, ["flights.airline_id", "flights.departure", "flights.arrival", "flights.price", "flights.duration"]
	            )
	          )
	        end
	      end
	    end
	end

	def create
		redirect_to flights_path
	end
end

app/helpers/flights_helper.rb
module FlightsHelper
	def flight_row(flight)
		[
      flight.airline.name,
      flight.departure, 
      flight.arrival,
      flight.price,
      flight.duration
    ]
  end
end

app/views/flights/index.html.erb
<% title "Flight Search Results" %>
<% description "Flight Search Results for Evolve Travel, Cheap Flights and Hotels" %>
<% keywords "flight search results, travel, Philippines, flights, hotels, deals, cheap" %>
<% set_meta_tags :og => {
  :title    => "Flight Search Results",
  :type     => 'product',
  :url      => request.url,
  :image    => image_path('og_logo.png')
  }
%>
<div class="container container-navbar-fix">
	<div class="row">
		<h1 class="col-xs-8">Search Results</h1>
		<h5 class="col-xs-4">Manila to Cebu | Saturday, December 28, 2013 | 1 Adult <a href="#">(Change)</a></h5>
	</div>
	<div class="progress">
	  <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
	    <span class="sr-only">60% Complete (warning)</span>
	  </div>
	</div>
	<!-- <div style="width: 100%; height: 5px; background: #F87431; overflow: hidden;"></div> -->

	<div class="row">
		<div class="btn-group col-xs-12">
		  <button type="button" class="btn btn-default col-xs-3" id="direct-transfer">Direct/Transfer</button>
		  <button type="button" class="btn btn-default col-xs-3" id="airlines">Select Airline</button>
		  <button type="button" class="btn btn-default col-xs-3" id="time">Select Time</button>
		  <button type="button" class="btn btn-default col-xs-3" id="date">Change Date</button>
		</div>
	</div>
	<div class="row">
		<div class="hidden" id="direct-transfer-panel">
		  <span class="col-xs-3" id="direct">
			<input type="checkbox"> Direct</input>
		  </span>
		  <span class="col-xs-3" id="transfer">
			<input type="checkbox"> Transfer</input>
		  </span>
		</div>
	</div>
	<div class="row">
		<div class="hidden" id="time-panel">
		  <span class="col-xs-3" id="direct">
			<input type="checkbox"> Direct</input>
		  </span>
		  <span class="col-xs-3" id="transfer">
			<input type="checkbox"> Transfer</input>
		  </span>
		</div>
	</div>
	<div class="row">
		<div class="hidden" id="date-panel">
		  <span class="col-xs-3" id="direct">
			<input type="checkbox"> Direct</input>
		  </span>
		  <span class="col-xs-3" id="transfer">
			<input type="checkbox"> Transfer</input>
		  </span>
		</div>
	</div>
	<div class="row">
		<div class="hidden" id="airline-panel">
		  <span class="col-xs-3" id="flypal">
			<input type="checkbox"> Philippine Airlines</input>
		  </span>
		  <span class="col-xs-3" id="airasiaph">
			<input type="checkbox"> Air Asia</input>
		  </span>
  		  <span class="col-xs-3" id="cebupacificair">
			<input type="checkbox"> Cebu Pacific Air</input>
		  </span>
  		  <span class="col-xs-3" id="tigerair">
			<input type="checkbox"> Tiger Air</input>
		  </span>
		</div>
	</div>
	<% if !@flights.empty? %>
    <%
      flight_params = {
        :format => "json", :datatable => true, :all => params[:all]
      }
    %>
	<table id="flights_datatable" class="table table-striped table-bordered" data-source="<%= flights_url(flight_params) %>">
		<thead>
		  <tr>
		    <th>Airline</th>
		    <th>Departure</th>
		    <th>Arrival</th>
		    <th>Price ($)</th>
		    <th>Duration</th>
		  </tr>
		</thead>
		<tbody>
		</tbody>
			<%# fmt = "%m/%d/%Y" %>
			<%# @flights.each do |f| %>
			  <!-- <tr>
			    <td><%#= Airline.find(f.airline_id).name %></td>
			    <td><%#= f.departure.strftime(fmt) %></td>
			    <td><%#= f.arrival.strftime(fmt) %></td>
			    <td><%#= f.price %></td>
			    <td><%#= f.duration %>
			    <a class='pull-right'><button href="/flight_searches" class="btn btn-danger" id="buy" role="button">BUY</button></a>
				</td>
			  </tr> -->
			<%# end %>
		</tbody>
	</table>
</div>
<% end %>
<script>
    $(document).ready(function() {
    	table_id = '#flights_datatable';
		$(table_id).dataTable({
		  "sPaginationType": "bootstrap",
		  "bFilter": false,
		  "bInfo": false,
		  "bLengthChange": false,
		  "bSortClasses": false,
		  "bProcessing": true,
		  "bServerSide": true,
		  "sAjaxSource": $(table_id).data('source')
		});
		$('#airlines').on('click', function() {
			var panels = ['time-panel','direct-transfer-panel','date-panel'];
			for (p in panels) {
				if(!$('#' + panels[p]).hasClass('hidden')) {
					$('#'+ panels[p]).toggleClass('hidden');
				};
			};
			$('#airline-panel').toggleClass('hidden');
		});	
		$('#direct-transfer').on('click', function() {
			var panels = ['time-panel','airline-panel','date-panel'];
			for (p in panels) {
				if(!$('#' + panels[p]).hasClass('hidden')) {
					$('#'+ panels[p]).toggleClass('hidden');
				};
			};
			$('#direct-transfer-panel').toggleClass('hidden')
		});	
		$('#time').on('click', function() {
			var panels = ['airline-panel','direct-transfer-panel','date-panel'];
			for (p in panels) {
				if(!$('#' + panels[p]).hasClass('hidden')) {
					$('#'+ panels[p]).toggleClass('hidden');
				};
			};
			$('#time-panel').toggleClass('hidden')
		});	
		$('#date').on('click', function() {
			var panels = ['time-panel','direct-transfer-panel','airline-panel'];
			for (p in panels) {
				if(!$('#' + panels[p]).hasClass('hidden')) {
					$('#'+ panels[p]).toggleClass('hidden');
				};
			};
			$('#date-panel').toggleClass('hidden')
		});	
    });
</script>